import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster"
import './globals.css'
const inter = Inter({ subsets: ["latin"] });
import {
  ClerkProvider,
} from '@clerk/nextjs'
import NavbarWrapper from "@/components/NavbarWrapper";
import { ThemeProvider } from "@/components/ThemeProvider";
import { dark } from "@clerk/themes";
export const metadata: Metadata = {
  title: "LinkSphare",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{
      baseTheme: dark,
    }}>
      <html lang="en">

        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <div className="min-h-screen bg-background flex flex-col">
              <NavbarWrapper />
              <main className="flex-1">{children}</main>
              {/* <Footer /> */}
              <Toaster />
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
